// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.16.3
// source: virtana/vdc/proto/collector/logs/v1/logs_service.proto

package v1

import (
	v1 "go.virtana.io/vdc/proto/logs/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExportLogsServiceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An array of ResourceLogs.
	ResourceLogs  []*v1.ResourceLogs `protobuf:"bytes,1,rep,name=resource_logs,json=resourceLogs,proto3" json:"resource_logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportLogsServiceRequest) Reset() {
	*x = ExportLogsServiceRequest{}
	mi := &file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportLogsServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportLogsServiceRequest) ProtoMessage() {}

func (x *ExportLogsServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportLogsServiceRequest.ProtoReflect.Descriptor instead.
func (*ExportLogsServiceRequest) Descriptor() ([]byte, []int) {
	return file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_rawDescGZIP(), []int{0}
}

func (x *ExportLogsServiceRequest) GetResourceLogs() []*v1.ResourceLogs {
	if x != nil {
		return x.ResourceLogs
	}
	return nil
}

type ExportLogsServiceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The details of a partially successful export request.
	PartialSuccess *ExportLogsPartialSuccess `protobuf:"bytes,1,opt,name=partial_success,json=partialSuccess,proto3" json:"partial_success,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExportLogsServiceResponse) Reset() {
	*x = ExportLogsServiceResponse{}
	mi := &file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportLogsServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportLogsServiceResponse) ProtoMessage() {}

func (x *ExportLogsServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportLogsServiceResponse.ProtoReflect.Descriptor instead.
func (*ExportLogsServiceResponse) Descriptor() ([]byte, []int) {
	return file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_rawDescGZIP(), []int{1}
}

func (x *ExportLogsServiceResponse) GetPartialSuccess() *ExportLogsPartialSuccess {
	if x != nil {
		return x.PartialSuccess
	}
	return nil
}

type ExportLogsPartialSuccess struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The number of rejected log records.
	RejectedLogRecords int64 `protobuf:"varint,1,opt,name=rejected_log_records,json=rejectedLogRecords,proto3" json:"rejected_log_records,omitempty"`
	// A developer-facing human-readable message in English.
	ErrorMessage  string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportLogsPartialSuccess) Reset() {
	*x = ExportLogsPartialSuccess{}
	mi := &file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportLogsPartialSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportLogsPartialSuccess) ProtoMessage() {}

func (x *ExportLogsPartialSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportLogsPartialSuccess.ProtoReflect.Descriptor instead.
func (*ExportLogsPartialSuccess) Descriptor() ([]byte, []int) {
	return file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_rawDescGZIP(), []int{2}
}

func (x *ExportLogsPartialSuccess) GetRejectedLogRecords() int64 {
	if x != nil {
		return x.RejectedLogRecords
	}
	return 0
}

func (x *ExportLogsPartialSuccess) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_virtana_vdc_proto_collector_logs_v1_logs_service_proto protoreflect.FileDescriptor

const file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_rawDesc = "" +
	"\n" +
	"6virtana/vdc/proto/collector/logs/v1/logs_service.proto\x12#virtana.vdc.proto.collector.logs.v1\x1a$virtana/vdc/proto/logs/v1/logs.proto\"h\n" +
	"\x18ExportLogsServiceRequest\x12L\n" +
	"\rresource_logs\x18\x01 \x03(\v2'.virtana.vdc.proto.logs.v1.ResourceLogsR\fresourceLogs\"\x83\x01\n" +
	"\x19ExportLogsServiceResponse\x12f\n" +
	"\x0fpartial_success\x18\x01 \x01(\v2=.virtana.vdc.proto.collector.logs.v1.ExportLogsPartialSuccessR\x0epartialSuccess\"q\n" +
	"\x18ExportLogsPartialSuccess\x120\n" +
	"\x14rejected_log_records\x18\x01 \x01(\x03R\x12rejectedLogRecords\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2\x99\x01\n" +
	"\vLogsService\x12\x89\x01\n" +
	"\x06Export\x12=.virtana.vdc.proto.collector.logs.v1.ExportLogsServiceRequest\x1a>.virtana.vdc.proto.collector.logs.v1.ExportLogsServiceResponse\"\x00B\x8d\x01\n" +
	"&io.virtana.vdc.proto.collector.logs.v1B\x10LogsServiceProtoP\x01Z)go.virtana.io/vdc/proto/collector/logs/v1\xaa\x02#Virtana.Vdc.Proto.Collector.Logs.V1b\x06proto3"

var (
	file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_rawDescOnce sync.Once
	file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_rawDescData []byte
)

func file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_rawDescGZIP() []byte {
	file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_rawDescOnce.Do(func() {
		file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_rawDesc), len(file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_rawDesc)))
	})
	return file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_rawDescData
}

var file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_goTypes = []any{
	(*ExportLogsServiceRequest)(nil),  // 0: virtana.vdc.proto.collector.logs.v1.ExportLogsServiceRequest
	(*ExportLogsServiceResponse)(nil), // 1: virtana.vdc.proto.collector.logs.v1.ExportLogsServiceResponse
	(*ExportLogsPartialSuccess)(nil),  // 2: virtana.vdc.proto.collector.logs.v1.ExportLogsPartialSuccess
	(*v1.ResourceLogs)(nil),           // 3: virtana.vdc.proto.logs.v1.ResourceLogs
}
var file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_depIdxs = []int32{
	3, // 0: virtana.vdc.proto.collector.logs.v1.ExportLogsServiceRequest.resource_logs:type_name -> virtana.vdc.proto.logs.v1.ResourceLogs
	2, // 1: virtana.vdc.proto.collector.logs.v1.ExportLogsServiceResponse.partial_success:type_name -> virtana.vdc.proto.collector.logs.v1.ExportLogsPartialSuccess
	0, // 2: virtana.vdc.proto.collector.logs.v1.LogsService.Export:input_type -> virtana.vdc.proto.collector.logs.v1.ExportLogsServiceRequest
	1, // 3: virtana.vdc.proto.collector.logs.v1.LogsService.Export:output_type -> virtana.vdc.proto.collector.logs.v1.ExportLogsServiceResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_init() }
func file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_init() {
	if File_virtana_vdc_proto_collector_logs_v1_logs_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_rawDesc), len(file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_goTypes,
		DependencyIndexes: file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_depIdxs,
		MessageInfos:      file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_msgTypes,
	}.Build()
	File_virtana_vdc_proto_collector_logs_v1_logs_service_proto = out.File
	file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_goTypes = nil
	file_virtana_vdc_proto_collector_logs_v1_logs_service_proto_depIdxs = nil
}
