// Copyright 2019, OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.16.3
// source: virtana/vdc/proto/traces/v1/traces.proto

package v1

import (
	v11 "go.opentelemetry.io/proto/otlp/common/v1"
	v1 "go.virtana.io/vdc/proto/resource/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpanFlags int32

const (
	SpanFlags_SPAN_FLAGS_DO_NOT_USE                 SpanFlags = 0
	SpanFlags_SPAN_FLAGS_TRACE_FLAGS_MASK           SpanFlags = 255
	SpanFlags_SPAN_FLAGS_CONTEXT_HAS_IS_REMOTE_MASK SpanFlags = 256
	SpanFlags_SPAN_FLAGS_CONTEXT_IS_REMOTE_MASK     SpanFlags = 512
)

// Enum value maps for SpanFlags.
var (
	SpanFlags_name = map[int32]string{
		0:   "SPAN_FLAGS_DO_NOT_USE",
		255: "SPAN_FLAGS_TRACE_FLAGS_MASK",
		256: "SPAN_FLAGS_CONTEXT_HAS_IS_REMOTE_MASK",
		512: "SPAN_FLAGS_CONTEXT_IS_REMOTE_MASK",
	}
	SpanFlags_value = map[string]int32{
		"SPAN_FLAGS_DO_NOT_USE":                 0,
		"SPAN_FLAGS_TRACE_FLAGS_MASK":           255,
		"SPAN_FLAGS_CONTEXT_HAS_IS_REMOTE_MASK": 256,
		"SPAN_FLAGS_CONTEXT_IS_REMOTE_MASK":     512,
	}
)

func (x SpanFlags) Enum() *SpanFlags {
	p := new(SpanFlags)
	*p = x
	return p
}

func (x SpanFlags) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SpanFlags) Descriptor() protoreflect.EnumDescriptor {
	return file_virtana_vdc_proto_traces_v1_traces_proto_enumTypes[0].Descriptor()
}

func (SpanFlags) Type() protoreflect.EnumType {
	return &file_virtana_vdc_proto_traces_v1_traces_proto_enumTypes[0]
}

func (x SpanFlags) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SpanFlags.Descriptor instead.
func (SpanFlags) EnumDescriptor() ([]byte, []int) {
	return file_virtana_vdc_proto_traces_v1_traces_proto_rawDescGZIP(), []int{0}
}

type Span_SpanKind int32

const (
	Span_SPAN_KIND_UNSPECIFIED Span_SpanKind = 0
	Span_SPAN_KIND_INTERNAL    Span_SpanKind = 1
	Span_SPAN_KIND_SERVER      Span_SpanKind = 2
	Span_SPAN_KIND_CLIENT      Span_SpanKind = 3
	Span_SPAN_KIND_PRODUCER    Span_SpanKind = 4
	Span_SPAN_KIND_CONSUMER    Span_SpanKind = 5
)

// Enum value maps for Span_SpanKind.
var (
	Span_SpanKind_name = map[int32]string{
		0: "SPAN_KIND_UNSPECIFIED",
		1: "SPAN_KIND_INTERNAL",
		2: "SPAN_KIND_SERVER",
		3: "SPAN_KIND_CLIENT",
		4: "SPAN_KIND_PRODUCER",
		5: "SPAN_KIND_CONSUMER",
	}
	Span_SpanKind_value = map[string]int32{
		"SPAN_KIND_UNSPECIFIED": 0,
		"SPAN_KIND_INTERNAL":    1,
		"SPAN_KIND_SERVER":      2,
		"SPAN_KIND_CLIENT":      3,
		"SPAN_KIND_PRODUCER":    4,
		"SPAN_KIND_CONSUMER":    5,
	}
)

func (x Span_SpanKind) Enum() *Span_SpanKind {
	p := new(Span_SpanKind)
	*p = x
	return p
}

func (x Span_SpanKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Span_SpanKind) Descriptor() protoreflect.EnumDescriptor {
	return file_virtana_vdc_proto_traces_v1_traces_proto_enumTypes[1].Descriptor()
}

func (Span_SpanKind) Type() protoreflect.EnumType {
	return &file_virtana_vdc_proto_traces_v1_traces_proto_enumTypes[1]
}

func (x Span_SpanKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Span_SpanKind.Descriptor instead.
func (Span_SpanKind) EnumDescriptor() ([]byte, []int) {
	return file_virtana_vdc_proto_traces_v1_traces_proto_rawDescGZIP(), []int{3, 0}
}

type Status_StatusCode int32

const (
	Status_STATUS_CODE_UNSET Status_StatusCode = 0
	Status_STATUS_CODE_OK    Status_StatusCode = 1
	Status_STATUS_CODE_ERROR Status_StatusCode = 2
)

// Enum value maps for Status_StatusCode.
var (
	Status_StatusCode_name = map[int32]string{
		0: "STATUS_CODE_UNSET",
		1: "STATUS_CODE_OK",
		2: "STATUS_CODE_ERROR",
	}
	Status_StatusCode_value = map[string]int32{
		"STATUS_CODE_UNSET": 0,
		"STATUS_CODE_OK":    1,
		"STATUS_CODE_ERROR": 2,
	}
)

func (x Status_StatusCode) Enum() *Status_StatusCode {
	p := new(Status_StatusCode)
	*p = x
	return p
}

func (x Status_StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status_StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_virtana_vdc_proto_traces_v1_traces_proto_enumTypes[2].Descriptor()
}

func (Status_StatusCode) Type() protoreflect.EnumType {
	return &file_virtana_vdc_proto_traces_v1_traces_proto_enumTypes[2]
}

func (x Status_StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status_StatusCode.Descriptor instead.
func (Status_StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_virtana_vdc_proto_traces_v1_traces_proto_rawDescGZIP(), []int{4, 0}
}

// TracesData represents the traces data that can be stored in a persistent storage,
// OR can be embedded by other protocols that transfer OTLP traces data but do
// not implement the OTLP protocol.
type TracesData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An array of ResourceSpans.
	ResourceSpans []*ResourceSpans `protobuf:"bytes,1,rep,name=resource_spans,json=resourceSpans,proto3" json:"resource_spans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TracesData) Reset() {
	*x = TracesData{}
	mi := &file_virtana_vdc_proto_traces_v1_traces_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TracesData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracesData) ProtoMessage() {}

func (x *TracesData) ProtoReflect() protoreflect.Message {
	mi := &file_virtana_vdc_proto_traces_v1_traces_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracesData.ProtoReflect.Descriptor instead.
func (*TracesData) Descriptor() ([]byte, []int) {
	return file_virtana_vdc_proto_traces_v1_traces_proto_rawDescGZIP(), []int{0}
}

func (x *TracesData) GetResourceSpans() []*ResourceSpans {
	if x != nil {
		return x.ResourceSpans
	}
	return nil
}

// A collection of ScopeSpans from a Resource.
type ResourceSpans struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource for the spans in this message.
	// If this field is not set then no resource info is known.
	Resource *v1.Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// A list of ScopeSpans that originate from a resource.
	ScopeSpans []*ScopeSpans `protobuf:"bytes,2,rep,name=scope_spans,json=scopeSpans,proto3" json:"scope_spans,omitempty"`
	// The Schema URL, if known.
	SchemaUrl     string `protobuf:"bytes,3,opt,name=schema_url,json=schemaUrl,proto3" json:"schema_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSpans) Reset() {
	*x = ResourceSpans{}
	mi := &file_virtana_vdc_proto_traces_v1_traces_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSpans) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSpans) ProtoMessage() {}

func (x *ResourceSpans) ProtoReflect() protoreflect.Message {
	mi := &file_virtana_vdc_proto_traces_v1_traces_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSpans.ProtoReflect.Descriptor instead.
func (*ResourceSpans) Descriptor() ([]byte, []int) {
	return file_virtana_vdc_proto_traces_v1_traces_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceSpans) GetResource() *v1.Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ResourceSpans) GetScopeSpans() []*ScopeSpans {
	if x != nil {
		return x.ScopeSpans
	}
	return nil
}

func (x *ResourceSpans) GetSchemaUrl() string {
	if x != nil {
		return x.SchemaUrl
	}
	return ""
}

// A collection of Spans produced by an InstrumentationScope.
type ScopeSpans struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The instrumentation scope information for the spans in this message.
	Scope *v11.InstrumentationScope `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// A list of Spans that originate from an instrumentation scope.
	Spans []*Span `protobuf:"bytes,2,rep,name=spans,proto3" json:"spans,omitempty"`
	// The Schema URL, if known.
	SchemaUrl     string `protobuf:"bytes,3,opt,name=schema_url,json=schemaUrl,proto3" json:"schema_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScopeSpans) Reset() {
	*x = ScopeSpans{}
	mi := &file_virtana_vdc_proto_traces_v1_traces_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopeSpans) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeSpans) ProtoMessage() {}

func (x *ScopeSpans) ProtoReflect() protoreflect.Message {
	mi := &file_virtana_vdc_proto_traces_v1_traces_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopeSpans.ProtoReflect.Descriptor instead.
func (*ScopeSpans) Descriptor() ([]byte, []int) {
	return file_virtana_vdc_proto_traces_v1_traces_proto_rawDescGZIP(), []int{2}
}

func (x *ScopeSpans) GetScope() *v11.InstrumentationScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *ScopeSpans) GetSpans() []*Span {
	if x != nil {
		return x.Spans
	}
	return nil
}

func (x *ScopeSpans) GetSchemaUrl() string {
	if x != nil {
		return x.SchemaUrl
	}
	return ""
}

// A Span represents a single operation performed by a single component of the system.
type Span struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TraceId                []byte                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId                 []byte                 `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	TraceState             string                 `protobuf:"bytes,3,opt,name=trace_state,json=traceState,proto3" json:"trace_state,omitempty"`
	ParentSpanId           []byte                 `protobuf:"bytes,4,opt,name=parent_span_id,json=parentSpanId,proto3" json:"parent_span_id,omitempty"`
	Flags                  uint32                 `protobuf:"fixed32,16,opt,name=flags,proto3" json:"flags,omitempty"`
	Name                   string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Kind                   Span_SpanKind          `protobuf:"varint,6,opt,name=kind,proto3,enum=virtana.vdc.proto.traces.v1.Span_SpanKind" json:"kind,omitempty"`
	StartTimeUnixNano      uint64                 `protobuf:"fixed64,7,opt,name=start_time_unix_nano,json=startTimeUnixNano,proto3" json:"start_time_unix_nano,omitempty"`
	EndTimeUnixNano        uint64                 `protobuf:"fixed64,8,opt,name=end_time_unix_nano,json=endTimeUnixNano,proto3" json:"end_time_unix_nano,omitempty"`
	Attributes             []*v11.KeyValue        `protobuf:"bytes,9,rep,name=attributes,proto3" json:"attributes,omitempty"`
	DroppedAttributesCount uint32                 `protobuf:"varint,10,opt,name=dropped_attributes_count,json=droppedAttributesCount,proto3" json:"dropped_attributes_count,omitempty"`
	Events                 []*Span_Event          `protobuf:"bytes,11,rep,name=events,proto3" json:"events,omitempty"`
	DroppedEventsCount     uint32                 `protobuf:"varint,12,opt,name=dropped_events_count,json=droppedEventsCount,proto3" json:"dropped_events_count,omitempty"`
	Links                  []*Span_Link           `protobuf:"bytes,13,rep,name=links,proto3" json:"links,omitempty"`
	DroppedLinksCount      uint32                 `protobuf:"varint,14,opt,name=dropped_links_count,json=droppedLinksCount,proto3" json:"dropped_links_count,omitempty"`
	Status                 *Status                `protobuf:"bytes,15,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Span) Reset() {
	*x = Span{}
	mi := &file_virtana_vdc_proto_traces_v1_traces_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Span) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span) ProtoMessage() {}

func (x *Span) ProtoReflect() protoreflect.Message {
	mi := &file_virtana_vdc_proto_traces_v1_traces_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span.ProtoReflect.Descriptor instead.
func (*Span) Descriptor() ([]byte, []int) {
	return file_virtana_vdc_proto_traces_v1_traces_proto_rawDescGZIP(), []int{3}
}

func (x *Span) GetTraceId() []byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

func (x *Span) GetSpanId() []byte {
	if x != nil {
		return x.SpanId
	}
	return nil
}

func (x *Span) GetTraceState() string {
	if x != nil {
		return x.TraceState
	}
	return ""
}

func (x *Span) GetParentSpanId() []byte {
	if x != nil {
		return x.ParentSpanId
	}
	return nil
}

func (x *Span) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Span) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Span) GetKind() Span_SpanKind {
	if x != nil {
		return x.Kind
	}
	return Span_SPAN_KIND_UNSPECIFIED
}

func (x *Span) GetStartTimeUnixNano() uint64 {
	if x != nil {
		return x.StartTimeUnixNano
	}
	return 0
}

func (x *Span) GetEndTimeUnixNano() uint64 {
	if x != nil {
		return x.EndTimeUnixNano
	}
	return 0
}

func (x *Span) GetAttributes() []*v11.KeyValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Span) GetDroppedAttributesCount() uint32 {
	if x != nil {
		return x.DroppedAttributesCount
	}
	return 0
}

func (x *Span) GetEvents() []*Span_Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Span) GetDroppedEventsCount() uint32 {
	if x != nil {
		return x.DroppedEventsCount
	}
	return 0
}

func (x *Span) GetLinks() []*Span_Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *Span) GetDroppedLinksCount() uint32 {
	if x != nil {
		return x.DroppedLinksCount
	}
	return 0
}

func (x *Span) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          Status_StatusCode      `protobuf:"varint,3,opt,name=code,proto3,enum=virtana.vdc.proto.traces.v1.Status_StatusCode" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_virtana_vdc_proto_traces_v1_traces_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_virtana_vdc_proto_traces_v1_traces_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_virtana_vdc_proto_traces_v1_traces_proto_rawDescGZIP(), []int{4}
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Status) GetCode() Status_StatusCode {
	if x != nil {
		return x.Code
	}
	return Status_STATUS_CODE_UNSET
}

type Span_Event struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TimeUnixNano           uint64                 `protobuf:"fixed64,1,opt,name=time_unix_nano,json=timeUnixNano,proto3" json:"time_unix_nano,omitempty"`
	Name                   string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Attributes             []*v11.KeyValue        `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty"`
	DroppedAttributesCount uint32                 `protobuf:"varint,4,opt,name=dropped_attributes_count,json=droppedAttributesCount,proto3" json:"dropped_attributes_count,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Span_Event) Reset() {
	*x = Span_Event{}
	mi := &file_virtana_vdc_proto_traces_v1_traces_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Span_Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span_Event) ProtoMessage() {}

func (x *Span_Event) ProtoReflect() protoreflect.Message {
	mi := &file_virtana_vdc_proto_traces_v1_traces_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span_Event.ProtoReflect.Descriptor instead.
func (*Span_Event) Descriptor() ([]byte, []int) {
	return file_virtana_vdc_proto_traces_v1_traces_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Span_Event) GetTimeUnixNano() uint64 {
	if x != nil {
		return x.TimeUnixNano
	}
	return 0
}

func (x *Span_Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Span_Event) GetAttributes() []*v11.KeyValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Span_Event) GetDroppedAttributesCount() uint32 {
	if x != nil {
		return x.DroppedAttributesCount
	}
	return 0
}

type Span_Link struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TraceId                []byte                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId                 []byte                 `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	TraceState             string                 `protobuf:"bytes,3,opt,name=trace_state,json=traceState,proto3" json:"trace_state,omitempty"`
	Attributes             []*v11.KeyValue        `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty"`
	DroppedAttributesCount uint32                 `protobuf:"varint,5,opt,name=dropped_attributes_count,json=droppedAttributesCount,proto3" json:"dropped_attributes_count,omitempty"`
	Flags                  uint32                 `protobuf:"fixed32,6,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Span_Link) Reset() {
	*x = Span_Link{}
	mi := &file_virtana_vdc_proto_traces_v1_traces_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Span_Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span_Link) ProtoMessage() {}

func (x *Span_Link) ProtoReflect() protoreflect.Message {
	mi := &file_virtana_vdc_proto_traces_v1_traces_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span_Link.ProtoReflect.Descriptor instead.
func (*Span_Link) Descriptor() ([]byte, []int) {
	return file_virtana_vdc_proto_traces_v1_traces_proto_rawDescGZIP(), []int{3, 1}
}

func (x *Span_Link) GetTraceId() []byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

func (x *Span_Link) GetSpanId() []byte {
	if x != nil {
		return x.SpanId
	}
	return nil
}

func (x *Span_Link) GetTraceState() string {
	if x != nil {
		return x.TraceState
	}
	return ""
}

func (x *Span_Link) GetAttributes() []*v11.KeyValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Span_Link) GetDroppedAttributesCount() uint32 {
	if x != nil {
		return x.DroppedAttributesCount
	}
	return 0
}

func (x *Span_Link) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

var File_virtana_vdc_proto_traces_v1_traces_proto protoreflect.FileDescriptor

const file_virtana_vdc_proto_traces_v1_traces_proto_rawDesc = "" +
	"\n" +
	"(virtana/vdc/proto/traces/v1/traces.proto\x12\x1bvirtana.vdc.proto.traces.v1\x1a*opentelemetry/proto/common/v1/common.proto\x1a,virtana/vdc/proto/resource/v1/resource.proto\"_\n" +
	"\n" +
	"TracesData\x12Q\n" +
	"\x0eresource_spans\x18\x01 \x03(\v2*.virtana.vdc.proto.traces.v1.ResourceSpansR\rresourceSpans\"\xc5\x01\n" +
	"\rResourceSpans\x12C\n" +
	"\bresource\x18\x01 \x01(\v2'.virtana.vdc.proto.resource.v1.ResourceR\bresource\x12H\n" +
	"\vscope_spans\x18\x02 \x03(\v2'.virtana.vdc.proto.traces.v1.ScopeSpansR\n" +
	"scopeSpans\x12\x1d\n" +
	"\n" +
	"schema_url\x18\x03 \x01(\tR\tschemaUrlJ\x06\b\xe8\a\x10\xe9\a\"\xaf\x01\n" +
	"\n" +
	"ScopeSpans\x12I\n" +
	"\x05scope\x18\x01 \x01(\v23.opentelemetry.proto.common.v1.InstrumentationScopeR\x05scope\x127\n" +
	"\x05spans\x18\x02 \x03(\v2!.virtana.vdc.proto.traces.v1.SpanR\x05spans\x12\x1d\n" +
	"\n" +
	"schema_url\x18\x03 \x01(\tR\tschemaUrl\"\xc4\n" +
	"\n" +
	"\x04Span\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\fR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\fR\x06spanId\x12\x1f\n" +
	"\vtrace_state\x18\x03 \x01(\tR\n" +
	"traceState\x12$\n" +
	"\x0eparent_span_id\x18\x04 \x01(\fR\fparentSpanId\x12\x14\n" +
	"\x05flags\x18\x10 \x01(\aR\x05flags\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12>\n" +
	"\x04kind\x18\x06 \x01(\x0e2*.virtana.vdc.proto.traces.v1.Span.SpanKindR\x04kind\x12/\n" +
	"\x14start_time_unix_nano\x18\a \x01(\x06R\x11startTimeUnixNano\x12+\n" +
	"\x12end_time_unix_nano\x18\b \x01(\x06R\x0fendTimeUnixNano\x12G\n" +
	"\n" +
	"attributes\x18\t \x03(\v2'.opentelemetry.proto.common.v1.KeyValueR\n" +
	"attributes\x128\n" +
	"\x18dropped_attributes_count\x18\n" +
	" \x01(\rR\x16droppedAttributesCount\x12?\n" +
	"\x06events\x18\v \x03(\v2'.virtana.vdc.proto.traces.v1.Span.EventR\x06events\x120\n" +
	"\x14dropped_events_count\x18\f \x01(\rR\x12droppedEventsCount\x12<\n" +
	"\x05links\x18\r \x03(\v2&.virtana.vdc.proto.traces.v1.Span.LinkR\x05links\x12.\n" +
	"\x13dropped_links_count\x18\x0e \x01(\rR\x11droppedLinksCount\x12;\n" +
	"\x06status\x18\x0f \x01(\v2#.virtana.vdc.proto.traces.v1.StatusR\x06status\x1a\xc4\x01\n" +
	"\x05Event\x12$\n" +
	"\x0etime_unix_nano\x18\x01 \x01(\x06R\ftimeUnixNano\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12G\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2'.opentelemetry.proto.common.v1.KeyValueR\n" +
	"attributes\x128\n" +
	"\x18dropped_attributes_count\x18\x04 \x01(\rR\x16droppedAttributesCount\x1a\xf4\x01\n" +
	"\x04Link\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\fR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\fR\x06spanId\x12\x1f\n" +
	"\vtrace_state\x18\x03 \x01(\tR\n" +
	"traceState\x12G\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2'.opentelemetry.proto.common.v1.KeyValueR\n" +
	"attributes\x128\n" +
	"\x18dropped_attributes_count\x18\x05 \x01(\rR\x16droppedAttributesCount\x12\x14\n" +
	"\x05flags\x18\x06 \x01(\aR\x05flags\"\x99\x01\n" +
	"\bSpanKind\x12\x19\n" +
	"\x15SPAN_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SPAN_KIND_INTERNAL\x10\x01\x12\x14\n" +
	"\x10SPAN_KIND_SERVER\x10\x02\x12\x14\n" +
	"\x10SPAN_KIND_CLIENT\x10\x03\x12\x16\n" +
	"\x12SPAN_KIND_PRODUCER\x10\x04\x12\x16\n" +
	"\x12SPAN_KIND_CONSUMER\x10\x05\"\xbc\x01\n" +
	"\x06Status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12B\n" +
	"\x04code\x18\x03 \x01(\x0e2..virtana.vdc.proto.traces.v1.Status.StatusCodeR\x04code\"N\n" +
	"\n" +
	"StatusCode\x12\x15\n" +
	"\x11STATUS_CODE_UNSET\x10\x00\x12\x12\n" +
	"\x0eSTATUS_CODE_OK\x10\x01\x12\x15\n" +
	"\x11STATUS_CODE_ERROR\x10\x02J\x04\b\x01\x10\x02*\x9c\x01\n" +
	"\tSpanFlags\x12\x19\n" +
	"\x15SPAN_FLAGS_DO_NOT_USE\x10\x00\x12 \n" +
	"\x1bSPAN_FLAGS_TRACE_FLAGS_MASK\x10\xff\x01\x12*\n" +
	"%SPAN_FLAGS_CONTEXT_HAS_IS_REMOTE_MASK\x10\x80\x02\x12&\n" +
	"!SPAN_FLAGS_CONTEXT_IS_REMOTE_MASK\x10\x80\x04Bp\n" +
	"\x1eio.virtana.vdc.proto.traces.v1B\vTracesProtoP\x01Z!go.virtana.io/vdc/proto/traces/v1\xaa\x02\x1bVirtana.Vdc.Proto.Traces.V1b\x06proto3"

var (
	file_virtana_vdc_proto_traces_v1_traces_proto_rawDescOnce sync.Once
	file_virtana_vdc_proto_traces_v1_traces_proto_rawDescData []byte
)

func file_virtana_vdc_proto_traces_v1_traces_proto_rawDescGZIP() []byte {
	file_virtana_vdc_proto_traces_v1_traces_proto_rawDescOnce.Do(func() {
		file_virtana_vdc_proto_traces_v1_traces_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_virtana_vdc_proto_traces_v1_traces_proto_rawDesc), len(file_virtana_vdc_proto_traces_v1_traces_proto_rawDesc)))
	})
	return file_virtana_vdc_proto_traces_v1_traces_proto_rawDescData
}

var file_virtana_vdc_proto_traces_v1_traces_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_virtana_vdc_proto_traces_v1_traces_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_virtana_vdc_proto_traces_v1_traces_proto_goTypes = []any{
	(SpanFlags)(0),                   // 0: virtana.vdc.proto.traces.v1.SpanFlags
	(Span_SpanKind)(0),               // 1: virtana.vdc.proto.traces.v1.Span.SpanKind
	(Status_StatusCode)(0),           // 2: virtana.vdc.proto.traces.v1.Status.StatusCode
	(*TracesData)(nil),               // 3: virtana.vdc.proto.traces.v1.TracesData
	(*ResourceSpans)(nil),            // 4: virtana.vdc.proto.traces.v1.ResourceSpans
	(*ScopeSpans)(nil),               // 5: virtana.vdc.proto.traces.v1.ScopeSpans
	(*Span)(nil),                     // 6: virtana.vdc.proto.traces.v1.Span
	(*Status)(nil),                   // 7: virtana.vdc.proto.traces.v1.Status
	(*Span_Event)(nil),               // 8: virtana.vdc.proto.traces.v1.Span.Event
	(*Span_Link)(nil),                // 9: virtana.vdc.proto.traces.v1.Span.Link
	(*v1.Resource)(nil),              // 10: virtana.vdc.proto.resource.v1.Resource
	(*v11.InstrumentationScope)(nil), // 11: opentelemetry.proto.common.v1.InstrumentationScope
	(*v11.KeyValue)(nil),             // 12: opentelemetry.proto.common.v1.KeyValue
}
var file_virtana_vdc_proto_traces_v1_traces_proto_depIdxs = []int32{
	4,  // 0: virtana.vdc.proto.traces.v1.TracesData.resource_spans:type_name -> virtana.vdc.proto.traces.v1.ResourceSpans
	10, // 1: virtana.vdc.proto.traces.v1.ResourceSpans.resource:type_name -> virtana.vdc.proto.resource.v1.Resource
	5,  // 2: virtana.vdc.proto.traces.v1.ResourceSpans.scope_spans:type_name -> virtana.vdc.proto.traces.v1.ScopeSpans
	11, // 3: virtana.vdc.proto.traces.v1.ScopeSpans.scope:type_name -> opentelemetry.proto.common.v1.InstrumentationScope
	6,  // 4: virtana.vdc.proto.traces.v1.ScopeSpans.spans:type_name -> virtana.vdc.proto.traces.v1.Span
	1,  // 5: virtana.vdc.proto.traces.v1.Span.kind:type_name -> virtana.vdc.proto.traces.v1.Span.SpanKind
	12, // 6: virtana.vdc.proto.traces.v1.Span.attributes:type_name -> opentelemetry.proto.common.v1.KeyValue
	8,  // 7: virtana.vdc.proto.traces.v1.Span.events:type_name -> virtana.vdc.proto.traces.v1.Span.Event
	9,  // 8: virtana.vdc.proto.traces.v1.Span.links:type_name -> virtana.vdc.proto.traces.v1.Span.Link
	7,  // 9: virtana.vdc.proto.traces.v1.Span.status:type_name -> virtana.vdc.proto.traces.v1.Status
	2,  // 10: virtana.vdc.proto.traces.v1.Status.code:type_name -> virtana.vdc.proto.traces.v1.Status.StatusCode
	12, // 11: virtana.vdc.proto.traces.v1.Span.Event.attributes:type_name -> opentelemetry.proto.common.v1.KeyValue
	12, // 12: virtana.vdc.proto.traces.v1.Span.Link.attributes:type_name -> opentelemetry.proto.common.v1.KeyValue
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_virtana_vdc_proto_traces_v1_traces_proto_init() }
func file_virtana_vdc_proto_traces_v1_traces_proto_init() {
	if File_virtana_vdc_proto_traces_v1_traces_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_virtana_vdc_proto_traces_v1_traces_proto_rawDesc), len(file_virtana_vdc_proto_traces_v1_traces_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_virtana_vdc_proto_traces_v1_traces_proto_goTypes,
		DependencyIndexes: file_virtana_vdc_proto_traces_v1_traces_proto_depIdxs,
		EnumInfos:         file_virtana_vdc_proto_traces_v1_traces_proto_enumTypes,
		MessageInfos:      file_virtana_vdc_proto_traces_v1_traces_proto_msgTypes,
	}.Build()
	File_virtana_vdc_proto_traces_v1_traces_proto = out.File
	file_virtana_vdc_proto_traces_v1_traces_proto_goTypes = nil
	file_virtana_vdc_proto_traces_v1_traces_proto_depIdxs = nil
}
