// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.16.3
// source: virtana/vdc/proto/collector/traces/v1/traces_service.proto

package v1

import (
	v1 "go.virtana.io/vdc/proto/traces/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExportTraceServiceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An array of ResourceSpans.
	ResourceSpans []*v1.ResourceSpans `protobuf:"bytes,1,rep,name=resource_spans,json=resourceSpans,proto3" json:"resource_spans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportTraceServiceRequest) Reset() {
	*x = ExportTraceServiceRequest{}
	mi := &file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportTraceServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportTraceServiceRequest) ProtoMessage() {}

func (x *ExportTraceServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportTraceServiceRequest.ProtoReflect.Descriptor instead.
func (*ExportTraceServiceRequest) Descriptor() ([]byte, []int) {
	return file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_rawDescGZIP(), []int{0}
}

func (x *ExportTraceServiceRequest) GetResourceSpans() []*v1.ResourceSpans {
	if x != nil {
		return x.ResourceSpans
	}
	return nil
}

type ExportTraceServiceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The details of a partially successful export request.
	PartialSuccess *ExportTracePartialSuccess `protobuf:"bytes,1,opt,name=partial_success,json=partialSuccess,proto3" json:"partial_success,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExportTraceServiceResponse) Reset() {
	*x = ExportTraceServiceResponse{}
	mi := &file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportTraceServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportTraceServiceResponse) ProtoMessage() {}

func (x *ExportTraceServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportTraceServiceResponse.ProtoReflect.Descriptor instead.
func (*ExportTraceServiceResponse) Descriptor() ([]byte, []int) {
	return file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_rawDescGZIP(), []int{1}
}

func (x *ExportTraceServiceResponse) GetPartialSuccess() *ExportTracePartialSuccess {
	if x != nil {
		return x.PartialSuccess
	}
	return nil
}

type ExportTracePartialSuccess struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The number of rejected spans.
	RejectedSpans int64 `protobuf:"varint,1,opt,name=rejected_spans,json=rejectedSpans,proto3" json:"rejected_spans,omitempty"`
	// A developer-facing human-readable message in English.
	ErrorMessage  string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportTracePartialSuccess) Reset() {
	*x = ExportTracePartialSuccess{}
	mi := &file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportTracePartialSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportTracePartialSuccess) ProtoMessage() {}

func (x *ExportTracePartialSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportTracePartialSuccess.ProtoReflect.Descriptor instead.
func (*ExportTracePartialSuccess) Descriptor() ([]byte, []int) {
	return file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_rawDescGZIP(), []int{2}
}

func (x *ExportTracePartialSuccess) GetRejectedSpans() int64 {
	if x != nil {
		return x.RejectedSpans
	}
	return 0
}

func (x *ExportTracePartialSuccess) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_virtana_vdc_proto_collector_traces_v1_traces_service_proto protoreflect.FileDescriptor

const file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_rawDesc = "" +
	"\n" +
	":virtana/vdc/proto/collector/traces/v1/traces_service.proto\x12%virtana.vdc.proto.collector.traces.v1\x1a(virtana/vdc/proto/traces/v1/traces.proto\"n\n" +
	"\x19ExportTraceServiceRequest\x12Q\n" +
	"\x0eresource_spans\x18\x01 \x03(\v2*.virtana.vdc.proto.traces.v1.ResourceSpansR\rresourceSpans\"\x87\x01\n" +
	"\x1aExportTraceServiceResponse\x12i\n" +
	"\x0fpartial_success\x18\x01 \x01(\v2@.virtana.vdc.proto.collector.traces.v1.ExportTracePartialSuccessR\x0epartialSuccess\"g\n" +
	"\x19ExportTracePartialSuccess\x12%\n" +
	"\x0erejected_spans\x18\x01 \x01(\x03R\rrejectedSpans\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2\xa0\x01\n" +
	"\fTraceService\x12\x8f\x01\n" +
	"\x06Export\x12@.virtana.vdc.proto.collector.traces.v1.ExportTraceServiceRequest\x1aA.virtana.vdc.proto.collector.traces.v1.ExportTraceServiceResponse\"\x00B\x95\x01\n" +
	"(io.virtana.vdc.proto.collector.traces.v1B\x12TracesServiceProtoP\x01Z+go.virtana.io/vdc/proto/collector/traces/v1\xaa\x02%Virtana.Vdc.Proto.Collector.Traces.V1b\x06proto3"

var (
	file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_rawDescOnce sync.Once
	file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_rawDescData []byte
)

func file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_rawDescGZIP() []byte {
	file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_rawDescOnce.Do(func() {
		file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_rawDesc), len(file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_rawDesc)))
	})
	return file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_rawDescData
}

var file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_goTypes = []any{
	(*ExportTraceServiceRequest)(nil),  // 0: virtana.vdc.proto.collector.traces.v1.ExportTraceServiceRequest
	(*ExportTraceServiceResponse)(nil), // 1: virtana.vdc.proto.collector.traces.v1.ExportTraceServiceResponse
	(*ExportTracePartialSuccess)(nil),  // 2: virtana.vdc.proto.collector.traces.v1.ExportTracePartialSuccess
	(*v1.ResourceSpans)(nil),           // 3: virtana.vdc.proto.traces.v1.ResourceSpans
}
var file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_depIdxs = []int32{
	3, // 0: virtana.vdc.proto.collector.traces.v1.ExportTraceServiceRequest.resource_spans:type_name -> virtana.vdc.proto.traces.v1.ResourceSpans
	2, // 1: virtana.vdc.proto.collector.traces.v1.ExportTraceServiceResponse.partial_success:type_name -> virtana.vdc.proto.collector.traces.v1.ExportTracePartialSuccess
	0, // 2: virtana.vdc.proto.collector.traces.v1.TraceService.Export:input_type -> virtana.vdc.proto.collector.traces.v1.ExportTraceServiceRequest
	1, // 3: virtana.vdc.proto.collector.traces.v1.TraceService.Export:output_type -> virtana.vdc.proto.collector.traces.v1.ExportTraceServiceResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_init() }
func file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_init() {
	if File_virtana_vdc_proto_collector_traces_v1_traces_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_rawDesc), len(file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_goTypes,
		DependencyIndexes: file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_depIdxs,
		MessageInfos:      file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_msgTypes,
	}.Build()
	File_virtana_vdc_proto_collector_traces_v1_traces_service_proto = out.File
	file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_goTypes = nil
	file_virtana_vdc_proto_collector_traces_v1_traces_service_proto_depIdxs = nil
}
